### ISSUE TITLE
Unicode escape sequence removed

### ISSUE THREAD

**Issue by agreedSkiing** [eemeli/prettier-plugin-properties#11]
Got a problem when using escape sequence my file contains only the properties below
```properties
tag.something = f\u00f6r
```
becomes
```properties
tag.something = för
```
should stay as
```properties
tag.something = f\u00f6r
```

## Running npx prettier
```bash
npx prettier --escape-non-latin1 --loglevel debug -c test.properties
[debug] normalized argv: {"_":["test.properties"],"cache":false,"color":true,"editorconfig":true,"escapeNonLatin1":true,"loglevel":"debug","configPrecedence":"cli-override","debugRepeat":0,"ignorePath":".prettierignore","plugins":[],"pluginSearchDirs":[],"check":true,"__raw":{"_":["test.properties"],"cache":false,"c":true,"color":true,"editorconfig":true,"escape-non-latin1":true,"loglevel":"debug","config-precedence":"cli-override","debug-repeat":0,"ignore-path":".prettierignore","plugin":[],"plugin-search-dir":[]}}
Checking formatting...
[debug] resolve config from 'test.properties'
[debug] loaded options `{"escapeNonLatin1":true}`
[debug] applied config-precedence (cli-override): {"escapeNonLatin1":true}
[warn] test.properties
[warn] Code style issues found in the above file. Forgot to run Prettier?
```

## Package.json
```json
{
  "devDependencies": {
    "prettier": "^2.8.7",
    "prettier-plugin-properties": "^0.2.0",
    "prettier-plugin-sh": "^0.12.8"
  }
}
```

**Comment by agreedSkiing** [comment]
Sorry me being stupid since that is not a correct character

**Comment by agreedSkiing** [comment]
Reponing with other data since it converts `\u00f6` to ö when it should not

**Comment by eemeli** [comment]
This currently counts as a feature; the escapes are normalised such that at least all Latin-1 characters (including `ö`) are included directly, as they are presumed to be supported by all .properties processors. Is this not the case with some tooling that you're interacting with?

**Comment by agreedSkiing** [comment]
We are using a spring boot application where we are generating certificates the code base that we are using is https://github.com/swedenconnect/ca-headless and the frontend app which might actually be the problem https://github.com/swedenconnect/ca-cmc-admin can't render the special characters if they arn't in `\u` format.

**Comment by eemeli** [comment]
That sounds rather surprising, as `ö` should not count as "special"; it's a valid Latin-1/ISO-8859-1 character. Spring's `@PropertySource` ultimately relies on `java.util.Properties`, which definitely supports that.

To change the current handling for this, I think I'd need to see some minimal example of a .properties file with `ö` being misparsed.

**Comment by agreedSkiing** [comment]
I think this is more a problem between the frontend spring boot app https://github.com/swedenconnect/ca-cmc-admin which I haven't tested the `åäö` character in and the certificate data that is sent from the backend https://github.com/swedenconnect/ca-headless which contains. 

P.S. Just tested the frontend application and yeah it has a problem when i added `åäö ÅÄÖ` in its title page
![bild](https://user-images.githubusercontent.com/93997033/228754698-df9242ae-636f-4321-941b-4fec0acffe4d.png)

**Comment by agreedSkiing** [comment]
And just checked the extracted certificate and that also displays the corrupt characters when using `åäö ÅÄÖ`

**Comment by agreedSkiing** [comment]
Right the files so here is a unformatted file taken from https://www.rapidtables.com/code/text/unicode-characters.html tabels
[test.properties.txt](https://github.com/eemeli/prettier-plugin-properties/files/11109250/test.properties.txt)

Then running the command below with the output on a copy of the file test.properties file.
```bash
$ npx prettier --loglevel=debug --escape-non-latin1=true --write test.formatted.with.true.properties
[debug] normalized argv: {"_":["test.formatted.with.true.properties"],"cache":false,"color":true,"editorconfig":true,"escapeNonLatin1":true,"write":true,"loglevel":"debug","configPrecedence":"cli-override","debugRepeat":0,"ignorePath":".prettierignore","plugins":[],"pluginSearchDirs":[],"__raw":{"_":["test.formatted.with.true.properties"],"cache":false,"color":true,"editorconfig":true,"escape-non-latin1":true,"write":true,"loglevel":"debug","config-precedence":"cli-override","debug-repeat":0,"ignore-path":".prettierignore","plugin":[],"plugin-search-dir":[]}}
[debug] resolve config from 'test.formatted.with.true.properties'
[debug] loaded options `{"escapeNonLatin1":true}`
[debug] applied config-precedence (cli-override): {"escapeNonLatin1":true}
test.formatted.with.true.properties 10ms
```
Result: [test.formatted.with.true.properties.txt](https://github.com/eemeli/prettier-plugin-properties/files/11109254/test.formatted.with.true.properties.txt)

And running the same with false flag on a copy of the file test file 
```bash 
$ npx prettier --loglevel=debug --escape-non-latin1=false --write test.formatted.with.false.properties
[debug] normalized argv: {"_":["test.formatted.with.false.properties"],"cache":false,"color":true,"editorconfig":true,"escapeNonLatin1":false,"write":true,"loglevel":"debug","configPrecedence":"cli-override","debugRepeat":0,"ignorePath":".prettierignore","plugins":[],"pluginSearchDirs":[],"__raw":{"_":["test.formatted.with.false.properties"],"cache":false,"color":true,"editorconfig":true,"escape-non-latin1":false,"write":true,"loglevel":"debug","config-precedence":"cli-override","debug-repeat":0,"ignore-path":".prettierignore","plugin":[],"plugin-search-dir":[]}}
[debug] resolve config from 'test.formatted.with.false.properties'
[debug] loaded options `{"escapeNonLatin1":true}`
[debug] applied config-precedence (cli-override): {"escapeNonLatin1":false}
test.formatted.with.false.properties 12ms
``` 
Result: [test.formatted.with.false.properties.txt](https://github.com/eemeli/prettier-plugin-properties/files/11109271/test.formatted.with.false.properties.txt)

Also by standard prettier does not seem to change the escaped character in a markdown file which might have something to with https://github.com/prettier/prettier/issues/163#issuecomment-274382761
```bash
$ npx prettier --loglevel=debug --escape-non-latin1=true --write markdown.test.md
[debug] normalized argv: {"_":["markdown.test.md"],"cache":false,"color":true,"editorconfig":true,"escapeNonLatin1":true,"write":true,"loglevel":"debug","configPrecedence":"cli-override","debugRepeat":0,"ignorePath":".prettierignore","plugins":[],"pluginSearchDirs":[],"__raw":{"_":["markdown.test.md"],"cache":false,"color":true,"editorconfig":true,"escape-non-latin1":true,"write":true,"loglevel":"debug","config-precedence":"cli-override","debug-repeat":0,"ignore-path":".prettierignore","plugin":[],"plugin-search-dir":[]}}
[debug] resolve config from 'markdown.test.md'
[debug] loaded options `{}`
[debug] applied config-precedence (cli-override): {"escapeNonLatin1":true}
markdown.test.md 56ms
$ npx prettier --loglevel=debug --escape-non-latin1=false --write markdown.test.md
[debug] normalized argv: {"_":["markdown.test.md"],"cache":false,"color":true,"editorconfig":true,"escapeNonLatin1":false,"write":true,"loglevel":"debug","configPrecedence":"cli-override","debugRepeat":0,"ignorePath":".prettierignore","plugins":[],"pluginSearchDirs":[],"__raw":{"_":["markdown.test.md"],"cache":false,"color":true,"editorconfig":true,"escape-non-latin1":false,"write":true,"loglevel":"debug","config-precedence":"cli-override","debug-repeat":0,"ignore-path":".prettierignore","plugin":[],"plugin-search-dir":[]}}
[debug] resolve config from 'markdown.test.md'
[debug] loaded options `{}`
[debug] applied config-precedence (cli-override): {"escapeNonLatin1":false}
markdown.test.md 56ms
```
[markdown.test.md](https://github.com/eemeli/prettier-plugin-properties/files/11109339/markdown.test.md)

**Comment by eemeli** [comment]
> P.S. Just tested the frontend application and yeah it has a problem when i added `åäö ÅÄÖ` in its title page ![bild](https://user-images.githubusercontent.com/93997033/228754698-df9242ae-636f-4321-941b-4fec0acffe4d.png)

This is [mojibake](https://en.wikipedia.org/wiki/Mojibake), i.e. you have an encoding problem. You're rendering UTF-8 encoded content as if it were ISO-8859-1. The value `åäö ÅÄÖ` has been parsed correctly from the .properties file, but some of your later processing of it is making incorrect assumptions about its encoding.

**Comment by agreedSkiing** [comment]
Going to write a bug report to the developers of the spring boot applications 👍
