### ISSUE TITLE
Sorting properties by alphabetical order

### ISSUE THREAD

**Issue by sylvain-lemouzy-pfx** [eemeli/prettier-plugin-properties#17]
Hello,

In my company, we'd like to keep properties entries ordered by alphabetical order.

Would you think this would it be a good candidate to improve your the plugin behavior? 

IMO this will improve the predictability of the output in the sense of it is less sensible on the initial order of the input. Hence, it will ensure same (logical) content -> same formatting output

**Comment by eemeli** [comment]
Reordering entries is definitely not a thing that ought to happen by default. Are there other Prettier plugins that allow for such an option?

**Comment by sylvain-lemouzy-pfx** [comment]
Yes I agree that some people might like to keep the original entry ordering. Properties files are nonsensitive on the ordering, this is why It may be a valid feature though.

The only plugin I can think of which do some kind of ordering is the [xml plugin](https://github.com/prettier/plugin-xml) with xmlSortAttributesByKey option (attributes ordering within elements is not important too).

**Comment by eemeli** [comment]
Ugh, just thought of something that probably makes this a non-starter: comments are not structurally assigned any connection to any specific lines; that association is entirely in the reader's head. For example, how would you reorder this?
```properties
foo = some value
# The foo is used in the frobnicator
bar = another value
```
And would it be the same as this?
```properties
foo = some value
# bar is used in the thingamajig
bar = another value
```

Not having that association explicitly defined in the file format is pretty problematic. For `yaml`, I ended up spending a lot of time figuring out a decent set of heuristics that _mostly_ get it the same way that people expect, but these days I'm much tempted to spend my time on defining [message resources](https://github.com/eemeli/message-resource-wg/) to provide a systematically better solution.

**Comment by sylvain-lemouzy-pfx** [comment]
One heuristic might be: comments are generally related to the property situated just below it. But yeah, that's not always true.

I do agree too, this is probably a good argument for a non-starter.  Let's close this issue at that point if you think it doesn't worth the effort.

Thank you anyway for your quick  and pertinent feedbacks. :slightly_smiling_face:
