### ISSUE TITLE
prettier-plugin-properties does not adhere to "proseWrap"

### ISSUE THREAD

**Issue by seancroach** [eemeli/prettier-plugin-properties#2]
For the time being, manually overriding "printWidth" to a large integer seems to have fixed the issue.

**Comment by eemeli** [comment]
As far as I can tell, `proseWrap` is a Prettier option that's only intended for markdown content. Are there any examples available of it being used for any other formats?

**Comment by seancroach** [comment]
Whoops! You're absolutely right; I had been under the impression that it was one of prettier's 'global' options.
